# Generated by Django 6.0.8 on 2026-09-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('service', models.CharField(choices=[('web', 'Web development'), ('design', 'Graphic design'), ('community', 'Community platforms'), ('tools', 'Internal tools'), ('film', 'Videography'), ('photo', 'Photography')], max_length=20)),
                ('message', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(blank=True, max_length=160)),
                ('service', models.CharField(choices=[('web', 'Web development'), ('design', 'Graphic design'), ('community', 'Community platforms'), ('tools', 'Internal tools'), ('film', 'Videography'), ('photo', 'Photography')], max_length=20)),
                ('summary', models.CharField(max_length=260)),
                ('cover', models.ImageField(upload_to='projects/covers/')),
                ('cover_alt', models.CharField(help_text='Describe the image for screen readers.', max_length=200)),
                ('challenge', models.TextField()),
                ('approach', models.TextField()),
                ('outcome', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='studio.project')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
