# Generated by Django 6.0.8 on 2026-09-12 10:23

import django.db.models.deletion
from django.db import migrations, models


def create_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model('studio', 'SiteSettings')
    SiteSettings.objects.get_or_create(pk=1)


def remove_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model('studio', 'SiteSettings')
    SiteSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Sababisha Africa', max_length=120)),
                ('site_tagline', models.CharField(blank=True, max_length=220)),
                ('site_description', models.TextField(blank=True, help_text='Used for search and social sharing descriptions.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X / Twitter URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SiteContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable internal name, e.g. hero or process.', max_length=80)),
                ('label', models.CharField(help_text='Editor-friendly section name.', max_length=120)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('action_label', models.CharField(blank=True, max_length=120)),
                ('action_url', models.CharField(blank=True, help_text='Use a relative path or anchor, e.g. #lets-vibe.', max_length=240)),
                ('image', models.ImageField(blank=True, upload_to='site-content/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='studio.sitesettings')),
            ],
            options={
                'verbose_name': 'content block',
                'verbose_name_plural': 'content blocks',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable internal name, e.g. primary-logo or hero-photo.', max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='site-assets/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.sitesettings')),
            ],
            options={
                'verbose_name': 'brand asset',
                'verbose_name_plural': 'brand assets',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.RunPython(create_site_settings, remove_site_settings),
    ]
