# Generated by Django 6.0.8 on 2026-09-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_sitesettings_sitecontentblock_siteasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_palette',
            field=models.CharField(choices=[('embers', 'Embers & Ink'), ('coastline', 'Coastline'), ('acacia', 'Acacia & Clay'), ('indigo', 'Indigo & Brass'), ('noir', 'Noir & Gold')], default='embers', help_text="Changes the public site's primary, ink, surface, and accent colours.", max_length=20),
        ),
    ]
