# Generated by Django 6.0.8 on 2026-09-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_sitesettings_theme_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='1', help_text='Number or label, e.g. 1, 2, 3', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'capability',
                'verbose_name_plural': 'capabilities',
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='1', help_text='Number or label, e.g. 1, 2, 3', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'process step',
                'verbose_name_plural': 'process steps',
                'ordering': ['sort_order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique internal slug, e.g. web-development, branding.', max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('summary_line', models.CharField(blank=True, help_text='Short punchy line, e.g. Built to do more.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the service.')),
                ('modal_description', models.TextField(blank=True, help_text='Text shown inside the service detail popup modal.')),
                ('tags', models.CharField(blank=True, help_text='Discipline tags, e.g. Websites / E-commerce / Web apps', max_length=240)),
                ('icon_svg', models.TextField(blank=True, help_text='Custom inline SVG for the service card icon. Leave blank for default icon.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'service offering',
                'verbose_name_plural': 'service offerings',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading',
            field=models.CharField(blank=True, default="Hey, we're Sababisha!", max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='capabilities_cta_label',
            field=models.CharField(blank=True, default='Book a sababisha.vibecheck', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='capabilities_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='capabilities_footer_text',
            field=models.CharField(blank=True, default='Want to explore your options?', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='capabilities_section_title',
            field=models.CharField(blank=True, default='My capabilities', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_footer_note',
            field=models.CharField(blank=True, default='More of an email person? Hit us up at:', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_heading',
            field=models.CharField(blank=True, default='Drop us a line', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_title',
            field=models.CharField(blank=True, default='Let’s vibe', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subtitle',
            field=models.CharField(blank=True, default="Ready to create something fresh? Let's chat.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='Sababisha Africa Studio · Nairobi, Kenya', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_mascot',
            field=models.ImageField(blank=True, help_text='Sababisha mascot artwork in footer (fallback: clean-up-your-brand.png).', upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_text',
            field=models.CharField(blank=True, default='Where we hang out online', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_subtagline',
            field=models.CharField(blank=True, default='SABABISHA AFRICA — INTENTIONAL BRANDING', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.CharField(blank=True, default='MAKE THINGS HAPPEN.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_photo',
            field=models.ImageField(blank=True, help_text='Studio director cover portrait (fallback: studio-founder.jpg).', upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_logo',
            field=models.ImageField(blank=True, help_text='Main zebra logo displayed in the welcome hero (fallback: sababisha-zebra-logo.png).', upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_cta_label',
            field=models.CharField(blank=True, default='Learn about our process', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_cta_url',
            field=models.CharField(blank=True, default='#our-process', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_step1_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_step1_heading',
            field=models.CharField(blank=True, default='First things First', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_step2_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_step2_heading',
            field=models.CharField(blank=True, default='Second things second', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_we_do_it_title',
            field=models.CharField(blank=True, default='How I do it', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_logo',
            field=models.ImageField(blank=True, help_text='Light logo shown in drawer navigation footer (fallback: sababisha-zebra-logo-light.png).', upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='owl_mascot',
            field=models.ImageField(blank=True, help_text='Horned owl mascot in How We Do It section (fallback: horned-owl.png).', upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='panther_mascot',
            field=models.ImageField(blank=True, help_text="Winged panther mascot in Let's Vibe section (fallback: cougar.png).", upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_cta_label',
            field=models.CharField(blank=True, default='Book your sababisha.vibecheck now', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_footer_text',
            field=models.CharField(blank=True, default='Need a tailored scope?', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_intro',
            field=models.TextField(blank=True, default='Choose a service to see what it includes. Every engagement is shaped around your goals, so pricing is quoted to fit the work.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_section_title',
            field=models.CharField(blank=True, default='Pricing', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_cta_label',
            field=models.CharField(blank=True, default='Book a sababisha.vibecheck', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_section_title',
            field=models.CharField(blank=True, default='My process', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='standing_warrior',
            field=models.ImageField(blank=True, help_text='Standing warrior graphic on process timeline (fallback: warrior-standing-clean.png).', upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_cta_bottom_line',
            field=models.CharField(blank=True, default='Schedule a vibe check.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_cta_top_line',
            field=models.CharField(blank=True, default='Start your brand journey.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_cta_top_text',
            field=models.TextField(blank=True, default='I help elevate existing brands and create new ones from scratch. I do it because I believe your brand should work as hard as you do.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_heading',
            field=models.TextField(blank=True, default='INTENTIONAL\nBRANDING\nFOR\nPASSIONATE\nBUSINESSES.', help_text='Main headline on the hero panel.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_we_do_body',
            field=models.TextField(blank=True, help_text='Paragraphs of copy for What We Do.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_we_do_cta_label',
            field=models.CharField(blank=True, default='See how we uncover your story.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_we_do_cta_url',
            field=models.CharField(blank=True, default='#how-we-do-it', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_we_do_heading',
            field=models.CharField(blank=True, default='SABABISHA.AFRICA IS A\nBRANDING AGENCY.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_we_do_title',
            field=models.CharField(blank=True, default='What I do', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whos_this_for_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whos_this_for_cta_bottom_line',
            field=models.CharField(blank=True, default='Schedule a vibe check.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whos_this_for_cta_top_line',
            field=models.CharField(blank=True, default='Start your brand journey.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whos_this_for_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whos_this_for_heading',
            field=models.CharField(blank=True, default='Are you a good fit?', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whos_this_for_title',
            field=models.CharField(blank=True, default='Who’s this for?', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='winged_lion',
            field=models.ImageField(blank=True, help_text="Winged lion mascot in Who's This For section (fallback: winged-lion.png).", upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='hello@sababisha.africa', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='x_url',
            field=models.URLField(blank=True, default='https://x.com', verbose_name='X / Twitter URL'),
        ),
    ]
