# Generated by Django 6.0.8 on 2026-09-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_seed_default_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffering',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Optional custom icon image for the service card.', upload_to='services/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bridging_warrior',
            field=models.ImageField(blank=True, help_text='Custom illustration for the warrior bridging What We Do and How We Do It (fallback: animated warrior canvas).', upload_to='brand/'),
        ),
    ]
