# Generated by Django 6.0.8 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0007_serviceoffering_icon_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="decorative_border",
            field=models.CharField(
                choices=[
                    ("classic", "Classic curved cutouts"),
                    ("square", "Clean square frame"),
                    ("rounded", "Soft rounded frame"),
                    ("deep-arch", "Deep arch cutouts"),
                    ("stepped", "Stepped corner cutouts"),
                    ("double", "Double-line frame"),
                    ("brackets", "Corner brackets"),
                ],
                default="classic",
                help_text="Changes the decorative frame used around homepage panels.",
                max_length=20,
            ),
        ),
    ]
