# Generated by Django 6.0.8 on 2026-09-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0009_alter_sitesettings_decorative_border"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="owl_mascot",
        ),
    ]
