# Generated by Django 6.0.8 on 2026-09-14 11:41

import studio.validators
from django.db import migrations, models


def migrate_legacy_service_keys(apps, schema_editor):
    """Keep existing projects and inquiries selectable after service key normalization."""
    replacements = {
        "web": "web-development",
        "design": "graphic-design",
        "community": "digital-storytelling",
        "tools": "service-systems",
        "film": "videography",
        "photo": "photography",
    }
    for model_name in ("Project", "Inquiry"):
        model = apps.get_model("studio", model_name)
        for old_key, new_key in replacements.items():
            model.objects.filter(service=old_key).update(service=new_key)


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_remove_sitesettings_owl_mascot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffering',
            name='icon_svg',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='service',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='service',
            field=models.CharField(max_length=60),
        ),
        migrations.RunPython(migrate_legacy_service_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sitesettings',
            name='capabilities_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200, validators=[studio.validators.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='how_cta_url',
            field=models.CharField(blank=True, default='#our-process', max_length=200, validators=[studio.validators.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pricing_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200, validators=[studio.validators.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='process_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200, validators=[studio.validators.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200, validators=[studio.validators.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='what_we_do_cta_url',
            field=models.CharField(blank=True, default='#how-we-do-it', max_length=200, validators=[studio.validators.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whos_this_for_cta_url',
            field=models.CharField(blank=True, default='#lets-vibe', max_length=200, validators=[studio.validators.validate_cta_url]),
        ),
    ]
