# Generated by Django 6.0.8 on 2026-09-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0011_harden_content_and_dynamic_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True)),
                ("available", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, help_text="Optional internal note, e.g. morning only.", max_length=160)),
            ],
            options={
                "verbose_name": "available appointment day",
                "verbose_name_plural": "available appointment days",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("organization", models.CharField(blank=True, max_length=160)),
                ("service", models.CharField(blank=True, max_length=60)),
                ("message", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("availability_day", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="appointment", to="studio.availabilityday")),
            ],
            options={"ordering": ["availability_day__date"]},
        ),
    ]
